jandan:
  baseUrl: "http://jandan.net"
  top: "/top"
  top4h: "/top-4h"
  topTucao: "/top-tucao"
  topOoxx: "/top-ooxx"
  topZoo: "/top-zoo"
  topComments: "/top-comments"
  top3days: "/top-3days"
  top7days: "/top-7days"
  cmds:
    {
      d:
     {
     url: "/top",
     name: "热榜",
     },
      d4:
     {
     url: "/top-4h",
     name: "4小时热门",
     },
      dt:
     {
     url: "/top-tucao",
     name: "吐槽",
     },
      ds:
     {
     url: "/top-ooxx",
     name: "随手拍",
     },
      dd:
     {
     url: "/top-zoo",
     name: "动物园",
     },
      dy:
     {
     url: "/top-comments",
     name: "优评",
     },
      d3:
     {
     url: "/top-3days",
     name: "3日热门",
     },
      d7:
     {
     url: "/top-7days",
     name: "7日热门",
     },
    }
  refreshInterval: 3600